"use client";
import { useState } from "react";
import { AmbientBackground } from "../../components/ambient-background";
import styles from "./docs.module.css";

type Item={title:string;text:string;note?:string};
type Step={eyebrow:string;title:string;intro:string;items:Item[];callout:[string,string]};
const steps:Step[]=[
{eyebrow:"PASSO 1 — MINERAR",title:"Encontrar e Preparar uma Empresa",intro:"Use o VerifyAds para encontrar empresas ativas e personalizar suas informações direto no sistema.",items:[
{title:"Acesse a página Minerar",text:"No menu lateral, clique em \"Minerar\". Configure os filtros desejados (cidade, capital, CNAE) e clique no botão \"MINERAR DADOS REAIS\". O sistema vai procurar automaticamente empresas ativas na Receita Federal.",note:"Menu lateral → Minerar → Configure filtros → MINERAR DADOS REAIS"},
{title:"Selecione uma empresa encontrada",text:"Quando as empresas aparecerem na tela, clique em qualquer uma delas. O Dossiê Empresarial abrirá — um modal com todos os dados da empresa (CNPJ, endereço, capital social, porte) verificados diretamente na Receita Federal.",note:"📋 Cada empresa aparece com um Trust Score de 0–100 indicando a qualidade do perfil."},
{title:"Edite o telefone e e-mail no campo \"Editar Informações\"",text:"No Dossiê Empresarial (modal central), na seção \"EDITAR INFORMAÇÕES\", você verá os campos de telefone e e-mail já preenchidos com os dados da Receita Federal. Substitua pelo SEU número de celular e SEU e-mail. Esses dados serão usados tanto no PDF quanto na landing page gerada.",note:"⚠️ IMPORTANTE: Coloque SEU celular no campo telefone. O Facebook pode enviar um SMS de verificação para esse número."},
{title:"Adicione o Token do Facebook (antes de gerar)",text:"Na seção \"VERIFICAÇÃO FACEBOOK\" do mesmo modal, cole o código da meta-tag que o Facebook gerou para você. O sistema extrai o token automaticamente. Faça isso ANTES de clicar em Gerar Link.",note:"Cole o código completo da meta-tag — o sistema extrai apenas o token sozinho."}],callout:["💡 Tudo acontece dentro do VerifyAds","Não é necessário usar nenhuma ferramenta externa. O telefone, e-mail e token do Facebook são editados direto no Dossiê Empresarial. O PDF e a landing page são gerados pelo próprio sistema."]},
{eyebrow:"PASSO 2 — PDF",title:"Gerar o PDF para Verificação por SMS",intro:"O VerifyAds gera o comprovante oficial com seus dados personalizados — pronto para enviar ao Facebook.",items:[
{title:"Edite o número de telefone no Dossiê",text:"Antes de gerar o PDF, certifique-se de que o campo \"Telefone\" no Dossiê Empresarial contém o SEU número de celular. Esse número será inserido automaticamente no PDF gerado.",note:"Campo de telefone no Dossiê → substitua pelo seu celular (DDD) NNNNN-NNNN"},
{title:"Clique em \"GERAR PDF\" no rodapé do Dossiê",text:"No rodapé do Dossiê Empresarial, clique no botão vermelho \"GERAR PDF\". O sistema vai criar automaticamente o comprovante oficial com os dados da empresa e com o número de telefone que você editou. O PDF será aberto em uma nova aba do navegador.",note:"Botão vermelho \"GERAR PDF\" → PDF abre automaticamente em nova aba"},
{title:"Salve o PDF no seu computador",text:"Com o PDF aberto na nova aba, use o atalho Ctrl+S (ou Cmd+S no Mac) para salvar o arquivo.",note:"Ctrl+S (Windows) ou Cmd+S (Mac) para salvar o PDF"},
{title:"Envie ao Facebook para verificação por SMS",text:"No Facebook → Configurações do Negócio → Verificação do Negócio, escolha o método de documento oficial e faça upload do PDF salvo.",note:"✅ SMS recebido! Insira o código de 6 dígitos na tela do Facebook para confirmar."}],callout:["💡 O PDF já vem pronto com seus dados","Não é necessário usar editores externos como ILovePDF. O VerifyAds já gera o PDF com o telefone e e-mail que você editou no Dossiê Empresarial. Basta clicar em Gerar PDF, salvar e enviar ao Facebook."]},{eyebrow:"PASSO 3 — LANDING PAGE",title:"Gerar o Site da Empresa no Seu Domínio",intro:"O VerifyAds cria e hospeda automaticamente a landing page da empresa no domínio que você conectar.",items:[
{title:"Conecte seu domínio primeiro",text:"Acesse Minha Área → aba \"Domínios\" → clique em \"+ Adicionar Domínio\". Insira seu domínio sem \"https://\". O sistema vai mostrar o registro CNAME que você precisa configurar no provedor do domínio.",note:"Minha Área → Domínios → + Adicionar Domínio"},
{title:"Configure o CNAME no seu provedor de domínio",text:"Acesse o painel onde comprou o domínio, vá em \"Gerenciar DNS\" e adicione um registro CNAME. O HOST deve ser \"@\" (raiz) e o VALOR deve ser \"cname.vercel-dns.com\".",note:"CNAME → @ → cname.vercel-dns.com (TTL: Auto)"},
{title:"Verifique a conexão no VerifyAds",text:"Após configurar o CNAME, volte ao VerifyAds → Minha Área → Domínios → clique em \"Verificar Conexão\". Quando aparecer o badge verde \"Verificado\", seu domínio está pronto para receber a landing page.",note:"✅ Badge verde \"Verificado\" = domínio pronto para uso."},
{title:"No Dossiê: adicione o Token do Facebook",text:"De volta ao Dossiê Empresarial, na seção \"VERIFICAÇÃO FACEBOOK\", cole o código da meta-tag gerado pelo Facebook. O token será embutido automaticamente no HTML da landing page. Faça isso ANTES de clicar em Gerar Link.",note:"⚠️ Cole o token ANTES de gerar o link."},
{title:"Selecione o domínio e clique em \"GERAR LINK & SALVAR\"",text:"Na coluna \"PÁGINA WHITE LABEL\" do Dossiê, selecione no menu suspenso o domínio que você conectou. Clique em \"GERAR LINK & SALVAR\". O sistema criará e publicará a landing page com os dados da empresa automaticamente.",note:"Dossiê → PÁGINA WHITE LABEL → Selecione o domínio → GERAR LINK & SALVAR"},
{title:"Verifique o site gerado pelo VerifyAds",text:"Após alguns instantes, o link do seu domínio aparecerá na tela. Acesse-o no navegador para confirmar que a landing page está publicada.",note:"Ctrl+U → Ctrl+F → pesquise \"facebook-domain-verification\""},
{title:"Verifique o domínio no Facebook",text:"Com a landing page publicada, vá ao Facebook → Configurações do Negócio → Segurança da Marca → Domínios → \"Adicionar\" → insira seu domínio → \"Verificar Domínio\".",note:"✅ Domínio verificado no Facebook! Agora você pode usar em campanhas de Ads."}],callout:["💡 Uma empresa = um domínio = exclusividade","Cada empresa só pode ser vinculada a um domínio por vez. Após gerar o link, essa empresa fica exclusiva para você — ela não aparecerá mais para outros usuários do VerifyAds na mineração."]},
{eyebrow:"PASSO 4 — FACEBOOK",title:"Verificar Empresa no Meta Business",intro:"Obtenha o token de verificação no Facebook e conclua a verificação do seu negócio.",items:[
{title:"Acesse o Meta Business Suite e vá em Configurações do Negócio",text:"Abra business.facebook.com e faça login. Clique no ícone de engrenagem ⚙️ para acessar Configurações do Negócio e procure \"Central de Segurança\" → \"Verificação do Negócio\".",note:"business.facebook.com → Configurações do Negócio → Central de Segurança → Verificação do Negócio"},
{title:"Gere o token: Segurança da Marca → Domínios",text:"No menu lateral, clique em \"Segurança da Marca\" → \"Domínios\" → \"+ Adicionar\". Escolha o método \"Adicione uma meta-tag ao código-fonte HTML\".",note:"<meta name=\"facebook-domain-verification\" content=\"abc123xyz...\" />"},
{title:"Copie o código e cole no VerifyAds",text:"No VerifyAds → Minerar → clique na empresa → seção \"VERIFICAÇÃO FACEBOOK\" → campo \"Token Meta-tag\" → cole o código. O sistema extrai automaticamente o token.",note:"⚠️ Não feche a aba do Facebook! Você precisará voltar para clicar em Verificar Domínio."},
{title:"Volte ao Facebook e clique em Verificar Domínio",text:"Com a landing page publicada, volte à aba do Facebook → Domínios → clique em \"Verificar Domínio\" ao lado do seu domínio.",note:"✅ Domínio verificado! A verificação do negócio está concluída."}],callout:["🔓 Facebook novo não mostra \"Verificar Domínio\"?","Contas novas do Meta Business não têm essa opção liberada automaticamente. O guia recomenda criar um App em developers.facebook.com para desbloquear a opção de verificação no Business Manager."]}];
const faqs:[string,string][]=[
["Preciso usar algum programa externo para editar o PDF?","Não! O VerifyAds gera o PDF já com os dados que você editou no Dossiê Empresarial. Basta colocar seu número de telefone no campo \"Editar Informações\", clicar em \"GERAR PDF\" e o sistema cria o arquivo pronto para download — sem precisar de ILovePDF, Adobe ou qualquer editor externo."],
["Onde coloco o número do meu celular para receber o SMS do Facebook?","No Dossiê Empresarial (Minerar → clique em uma empresa), na seção \"EDITAR INFORMAÇÕES\", há um campo de telefone. Substitua o número original da empresa pelo seu celular."],
["O site da empresa é criado automaticamente pelo VerifyAds?","Sim! Após conectar seu domínio e clicar em \"GERAR LINK & SALVAR\" no Dossiê, o VerifyAds cria e publica automaticamente a landing page da empresa no seu domínio."],
["Onde coloco o token do Facebook no VerifyAds?","No Dossiê Empresarial, na seção \"VERIFICAÇÃO FACEBOOK\", campo \"Token Meta-tag\". Cole o código completo que o Facebook gerou."],
["Preciso inserir o token antes ou depois de gerar o link?","ANTES. Para evitar retrabalho, sempre insira o token do Facebook no Dossiê antes de clicar em Gerar Link."],
["Como confirmo que o token está na landing page?","Acesse seu domínio → \"Ver código-fonte\" (ou Ctrl+U) → Ctrl+F para buscar \"facebook-domain-verification\"."],
["Por que o Facebook não mostra a opção de verificar empresa?","Contas novas do Meta Business não têm esse recurso automaticamente. O guia recomenda criar um App em developers.facebook.com."],
["Posso usar a mesma empresa em dois domínios?","Não. Cada empresa (CNPJ) é exclusiva — pode ser vinculada a apenas um domínio por vez."]
];const tips:[string,string,string][]=[
["Edite antes de gerar","Coloque seu telefone e o token do Facebook no Dossiê ANTES de clicar em Gerar PDF ou Gerar Link.","yellow"],
["CNPJ exclusivo","Assim que vincular uma empresa a um domínio, ela sai da mineração para todos. Exclusividade garantida.","blue"],
["Conta nova no Facebook?","Crie um App em developers.facebook.com para desbloquear a opção de verificar empresa no Business Manager.","purple"]
];

export default function DocsPage(){
 const [active,setActive]=useState(0); const [openFaq,setOpenFaq]=useState<number|null>(null); const step=steps[active];
 const goFaq=()=>document.getElementById("faq")?.scrollIntoView({behavior:"smooth",block:"start"});
 return <main className={styles.page}><AmbientBackground/><div className={styles.shell}>
  <header className={styles.header}><div><span className={styles.eyebrow}>PAINEL DE CONTROLE</span><h1>Central de Ajuda</h1><p>Guia completo para verificar sua empresa no Facebook Ads usando o VerifyAds</p></div><div className={styles.user}>Olá, <strong>Usuário</strong></div></header>
  <div className={styles.intro}><strong>📌 Tudo acontece dentro do VerifyAds:</strong> edite o telefone, gere o PDF, crie o site da empresa e injete o token do Facebook — sem precisar de nenhuma ferramenta externa. Siga os 4 passos abaixo em ordem.</div>
  <nav className={styles.tabs} aria-label="Etapas do guia">{["1. Preparar Empresa","2. Gerar PDF","3. Landing Page","4. Verificar no Facebook"].map((label,i)=><button key={label} className={active===i?styles.activeTab:""} onClick={()=>setActive(i)}>{label}</button>)}<button onClick={goFaq}>FAQ</button></nav>
  <section className={styles.step}><div className={styles.stepHead}><span>{step.eyebrow}</span><h2>{step.title}</h2><p>{step.intro}</p></div>
   <div className={styles.cards}>{step.items.map((item,i)=><article key={item.title} className={styles.card}><div className={styles.number}>{i+1}</div><h3>{item.title}</h3><p>{item.text}</p>{item.note&&<div className={styles.note}>{item.note}</div>}</article>)}</div>
   <div className={styles.callout}><h3>{step.callout[0]}</h3><p>{step.callout[1]}</p></div>
  </section>
  <section className={styles.tips}>{tips.map(([title,text,tone])=><article key={title} className={styles["tip_"+tone]}><h3>{title}</h3><p>{text}</p></article>)}</section>
  <section id="faq" className={styles.faq}><h2>Perguntas Frequentes</h2><div>{faqs.map(([q,a],i)=><article key={q} className={styles.faqItem}><button aria-expanded={openFaq===i} onClick={()=>setOpenFaq(openFaq===i?null:i)}><span>{q}</span><b>{openFaq===i?"−":"+"}</b></button>{openFaq===i&&<p>{a}</p>}</article>)}</div></section>
 </div></main>;
}